### ISSUE TITLE
Cannot import OrbitPlotter3D

### ISSUE THREAD

**Issue by pbhuter** [pleiszenburg/hapsira#1]
🐞 **Hapsira 0.18-dev migration from Poliastro 0.17 throws error**

🖥 **ImportError: cannot import name 'OrbitPlotter3D' from 'hapsira.plotting' (C:\Users\paulb\AppData\Local\Programs\Python\Python38\lib\site-packages\hapsira\plotting\__init__.py)**

**Comment by kerel-fs** [comment]
hapsira is based on poliastro `main` as of the date of its archival, October 14 2023, commit [21fd771](https://github.com/poliastro/poliastro/commit/21fd7719e89a7d22b4eac63141a60a7f1b01768c). Thus it includes already the new plotter architecture. For a full list of changes between the last poliastro release and the current hapsira `main` branch have a look at the [Changelog](https://hapsira.readthedocs.io/en/latest/changelog.html#hapsira-0-18-0-2023-12-xx) for the upcoming first release of hapsira:
> FEATURE: New plotters architecture with backend support, see [poliastro #1545](https://github.com/poliastro/poliastro/pull/1545)

The `OrbitPlotter3D` class is gone in favor of a unified orbit plotter. I'd recommend to look into this Pull Request to find documentation on the new plotter API.
